statechain_entity = "http://127.0.0.1:8000"
#statechain_entity = "http://j23wevaeducxuy3zahd6bpn4x76cymwz2j3bdixv7ow4awjrg5p6jaid.onion"
chain_backend = "core"
core_rpc_url = "http://127.0.0.1:38332"
core_rpc_auth = "userpass"
core_rpc_user = "bitcoinrpc"
core_rpc_password = "bitcoinrpc"
#core_rpc_cookie_file = ""
network = "signet"
fee_rate_tolerance = 5
database_file="wallet.db"
confirmation_target = 2
#tor_proxy = "socks5h://localhost:9050"
# max fee rate in sat/vbyte
# if the fee rate is higher than this, the transaction will use this max fee rate
max_fee_rate = 1
