[workspace]
members = ["clients/apps/rust", "clients/libs/rust", "server", "lib", "token-server", "clients/tests/rust", "token-server-v2"]
exclude = ["docs", "keylistCron"]
resolver = "2"

[patch.crates-io]
bitcoin = { git = "https://github.com/w0xlt/rust-bitcoin", branch = "inquisition-bip448-support-0.30.2" }
bitcoin-private = { git = "https://github.com/w0xlt/rust-bitcoin", branch = "inquisition-bip448-support-0.30.2" }
bitcoin_hashes = { git = "https://github.com/w0xlt/rust-bitcoin", branch = "inquisition-bip448-support-0.30.2" }
secp256k1 = { git = "https://github.com/w0xlt/rust-secp256k1.git", branch = "mercury-blinded-musig-port" }
