pub(super) type ConstraintSpec = (
    &'static str,
    &'static str,
    &'static str,
    &'static [&'static str],
    &'static str,
);
pub(super) const MERCURY_CONSTRAINTS: &[ConstraintSpec] = &[
    (
        "bip448_signature_data",
        "bip448_signature_data_pkey",
        "p",
        &["id"],
        "PRIMARY KEY (id)",
    ),
    (
        "bip448_signature_data",
        "bip448_signature_data_signing_id_check",
        "c",
        &["signing_id"],
        "CHECK (signing_id ~ '^[0-9a-f]{64}$')",
    ),
    (
        "bip448_signature_data",
        "bip448_signature_data_signing_id_ukey",
        "u",
        &["statechain_id", "signing_id"],
        "UNIQUE (statechain_id, signing_id)",
    ),
    (
        "lightning_latch",
        "lightning_latch_pkey",
        "p",
        &["id"],
        "PRIMARY KEY (id)",
    ),
    (
        "lightning_latch",
        "unique_statechain_sender_batch",
        "u",
        &["statechain_id", "batch_id"],
        "UNIQUE (statechain_id, batch_id)",
    ),
    (
        "signing_nonce_leases",
        "signing_nonce_leases_lease_token_check",
        "c",
        &["lease_token"],
        "CHECK (lease_token ~ '^[0-9a-f]{32}$')",
    ),
    (
        "signing_nonce_leases",
        "signing_nonce_leases_pkey",
        "p",
        &["statechain_id"],
        "PRIMARY KEY (statechain_id)",
    ),
    (
        "signing_nonce_leases",
        "signing_nonce_leases_signing_id_check",
        "c",
        &["signing_id"],
        "CHECK (signing_id ~ '^[0-9a-f]{64}$')",
    ),
    (
        "statechain_data",
        "statechain_data_pkey",
        "p",
        &["id"],
        "PRIMARY KEY (id)",
    ),
    (
        "statechain_data",
        "statechain_data_server_public_key_ukey",
        "u",
        &["server_public_key"],
        "UNIQUE (server_public_key)",
    ),
    (
        "statechain_data",
        "statechain_data_statechain_id_key",
        "u",
        &["statechain_id"],
        "UNIQUE (statechain_id)",
    ),
    (
        "statechain_data",
        "statechain_data_token_id_key",
        "u",
        &["token_id"],
        "UNIQUE (token_id)",
    ),
    (
        "statechain_transfer",
        "statechain_transfer_pkey",
        "p",
        &["id"],
        "PRIMARY KEY (id)",
    ),
    (
        "statechain_transfer",
        "statechain_transfer_statechain_id_key",
        "u",
        &["statechain_id"],
        "UNIQUE (statechain_id)",
    ),
    ("tokens", "tokens_pkey", "p", &["id"], "PRIMARY KEY (id)"),
    (
        "tokens",
        "tokens_token_id_key",
        "u",
        &["token_id"],
        "UNIQUE (token_id)",
    ),
];

pub(super) const LOCKBOX_CONSTRAINTS: &[ConstraintSpec] = &[
    ("bip448_keyupdate_receipt","bip448_keyupdate_receipt_accepted_sig_count_check","c",&["accepted_sig_count"],"CHECK (accepted_sig_count >= 0)"),
    ("bip448_keyupdate_receipt","bip448_keyupdate_receipt_check","c",&["resulting_key_generation","previous_key_generation"],"CHECK (resulting_key_generation = (previous_key_generation + 1))"),
    ("bip448_keyupdate_receipt","bip448_keyupdate_receipt_pkey","p",&["statechain_id","operation_id"],"PRIMARY KEY (statechain_id, operation_id)"),
    ("bip448_keyupdate_receipt","bip448_keyupdate_receipt_previous_key_generation_check","c",&["previous_key_generation"],"CHECK (previous_key_generation >= 0)"),
    ("bip448_keyupdate_receipt","bip448_keyupdate_receipt_statechain_id_fkey","f",&["statechain_id"],"FOREIGN KEY (statechain_id) REFERENCES generated_public_key(statechain_id) ON DELETE CASCADE"),
    ("bip448_nonce_state","bip448_nonce_state_challenge_check","c",&["challenge"],"CHECK (challenge IS NULL OR challenge ~ '^[0-9a-f]{64}$')"),
    ("bip448_nonce_state","bip448_nonce_state_claim_check","c",&["challenge","negate_seckey","partial_sig"],"CHECK (challenge IS NULL AND negate_seckey IS NULL AND partial_sig IS NULL OR challenge IS NOT NULL AND negate_seckey IS NOT NULL)"),
    ("bip448_nonce_state","bip448_nonce_state_key_generation_nonnegative","c",&["key_generation"],"CHECK (key_generation >= 0)"),
    ("bip448_nonce_state","bip448_nonce_state_negate_check","c",&["negate_seckey"],"CHECK (negate_seckey IS NULL OR (negate_seckey = ANY (ARRAY[0, 1])))"),
    ("bip448_nonce_state","bip448_nonce_state_parent","f",&["statechain_id"],"FOREIGN KEY (statechain_id) REFERENCES generated_public_key(statechain_id) ON DELETE CASCADE"),
    ("bip448_nonce_state","bip448_nonce_state_pkey","p",&["id"],"PRIMARY KEY (id)"),
    ("bip448_nonce_state","bip448_nonce_state_signing_id_check","c",&["signing_id"],"CHECK (signing_id ~ '^[0-9a-f]{64}$')"),
    ("bip448_nonce_state","bip448_nonce_state_unique","u",&["statechain_id","signing_id"],"UNIQUE (statechain_id, signing_id)"),
    ("generated_public_key","generated_public_key_key_generation_nonnegative","c",&["key_generation"],"CHECK (key_generation >= 0)"),
    ("generated_public_key","generated_public_key_pkey","p",&["id"],"PRIMARY KEY (id)"),
    ("generated_public_key","generated_public_key_public_key_key","u",&["public_key"],"UNIQUE (public_key)"),
    ("generated_public_key","generated_public_key_sig_count_nonnegative","c",&["sig_count"],"CHECK (sig_count >= 0)"),
];

pub(super) type IndexSpec = (
    &'static str,
    &'static str,
    bool,
    bool,
    &'static [&'static str],
    Option<&'static str>,
);
pub(super) const MERCURY_INDEXES: &[IndexSpec] = &[
    (
        "bip448_signature_data",
        "bip448_signature_data_one_incomplete_per_statechain_idx",
        true,
        false,
        &["statechain_id"],
        Some("server_partial_sig IS NULL"),
    ),
    (
        "bip448_signature_data",
        "bip448_signature_data_pkey",
        true,
        true,
        &["id"],
        None,
    ),
    (
        "bip448_signature_data",
        "bip448_signature_data_signing_id_ukey",
        true,
        false,
        &["statechain_id", "signing_id"],
        None,
    ),
    (
        "lightning_latch",
        "lightning_latch_pkey",
        true,
        true,
        &["id"],
        None,
    ),
    (
        "lightning_latch",
        "unique_statechain_sender_batch",
        true,
        false,
        &["statechain_id", "batch_id"],
        None,
    ),
    (
        "signing_nonce_leases",
        "signing_nonce_leases_pkey",
        true,
        true,
        &["statechain_id"],
        None,
    ),
    (
        "statechain_data",
        "statechain_data_pkey",
        true,
        true,
        &["id"],
        None,
    ),
    (
        "statechain_data",
        "statechain_data_server_public_key_ukey",
        true,
        false,
        &["server_public_key"],
        None,
    ),
    (
        "statechain_data",
        "statechain_data_statechain_id_key",
        true,
        false,
        &["statechain_id"],
        None,
    ),
    (
        "statechain_data",
        "statechain_data_token_id_key",
        true,
        false,
        &["token_id"],
        None,
    ),
    (
        "statechain_transfer",
        "statechain_transfer_pkey",
        true,
        true,
        &["id"],
        None,
    ),
    (
        "statechain_transfer",
        "statechain_transfer_statechain_id_key",
        true,
        false,
        &["statechain_id"],
        None,
    ),
    ("tokens", "tokens_pkey", true, true, &["id"], None),
    (
        "tokens",
        "tokens_token_id_key",
        true,
        false,
        &["token_id"],
        None,
    ),
];
pub(super) const LOCKBOX_INDEXES: &[IndexSpec] = &[
    (
        "bip448_keyupdate_receipt",
        "bip448_keyupdate_receipt_pkey",
        true,
        true,
        &["statechain_id", "operation_id"],
        None,
    ),
    (
        "bip448_nonce_state",
        "bip448_nonce_state_pkey",
        true,
        true,
        &["id"],
        None,
    ),
    (
        "bip448_nonce_state",
        "bip448_nonce_state_unique",
        true,
        false,
        &["statechain_id", "signing_id"],
        None,
    ),
    (
        "generated_public_key",
        "generated_public_key_pkey",
        true,
        true,
        &["id"],
        None,
    ),
    (
        "generated_public_key",
        "generated_public_key_public_key_key",
        true,
        false,
        &["public_key"],
        None,
    ),
    (
        "generated_public_key",
        "generated_public_key_statechain_id_key",
        true,
        false,
        &["statechain_id"],
        None,
    ),
];
